# Generated by Django 4.1.7 on 2023-03-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
