# Generated by Django 4.1.7 on 2023-03-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_upload_alter_blog_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='introduce',
            new_name='content',
        ),
    ]
